apiVersion: v1
kind: Namespace
metadata:
  name: innov-namespace
--- 
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: innov-namespace
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

--- 

